/* Generates committed responsive AVIF/WebP assets from the raster masters. */
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { basename, dirname, extname, join, relative, resolve } from "node:path";

import sharp from "sharp";

const ROOT = resolve(".");
const OUTPUT_ROOT = resolve("public/_generated");
const MANIFEST_FILE = resolve("src/assets/generatedImageManifest.ts");
const SOURCE_GROUPS = ["projects", "me-pictures"];
const SOURCE_EXTENSIONS = new Set([".png", ".jpg", ".jpeg"]);
const TARGET_WIDTHS = [400, 800, 1200];
const MIN_SOURCE_EDGE = 256;
const CHECK_ONLY = process.argv.includes("--check");

// Converts an absolute public file path into the root-relative URL used by React.
function publicUrl(filePath) {
  return `/${relative(resolve("public"), filePath).split("\\").join("/")}`;
}

// Finds only top-level project and personal raster masters. Icon directories
// and SVG assets are intentionally outside these source groups.
async function sourceFiles() {
  const files = [];

  for (const group of SOURCE_GROUPS) {
    const directory = resolve("public", group);
    const entries = await readdir(directory, { withFileTypes: true });

    for (const entry of entries) {
      const extension = extname(entry.name).toLowerCase();
      if (entry.isFile() && SOURCE_EXTENSIONS.has(extension)) {
        files.push({ group, filePath: join(directory, entry.name) });
      }
    }
  }

  return files.sort((a, b) => a.filePath.localeCompare(b.filePath));
}

// Chooses useful widths without ever enlarging a source image. Narrow portrait
// images still receive one derivative at their natural width.
function derivativeWidths(sourceWidth) {
  const widths = TARGET_WIDTHS.filter(width => width <= sourceWidth);
  if (widths.length === 0) widths.push(sourceWidth);
  return widths;
}

// Writes a generated binary or verifies that the committed file is identical.
async function persistDerivative(filePath, contents) {
  if (CHECK_ONLY) {
    try {
      const existing = await readFile(filePath);
      if (!existing.equals(contents)) {
        throw new Error(`Generated image is stale: ${relative(ROOT, filePath)}`);
      }
    } catch (error) {
      if (error?.code === "ENOENT") {
        throw new Error(`Generated image is missing: ${relative(ROOT, filePath)}`);
      }
      throw error;
    }
    return;
  }

  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, contents);
}

// Builds all derivatives for one master and returns its typed manifest entry.
async function generateEntry({ group, filePath }) {
  const image = sharp(filePath, { failOn: "error" });
  const metadata = await image.metadata();
  const sourceWidth = metadata.width ?? 0;
  const sourceHeight = metadata.height ?? 0;

  if (!sourceWidth || !sourceHeight || Math.max(sourceWidth, sourceHeight) < MIN_SOURCE_EDGE) {
    return null;
  }

  const stem = basename(filePath, extname(filePath));
  const outputDirectory = resolve(OUTPUT_ROOT, group, stem);
  const variants = { avif: [], webp: [] };

  for (const width of derivativeWidths(sourceWidth)) {
    const avifPath = resolve(outputDirectory, `${width}.avif`);
    const webpPath = resolve(outputDirectory, `${width}.webp`);
    const resized = sharp(filePath).resize({ width, withoutEnlargement: true });
    const [avif, webp] = await Promise.all([
      resized.clone().avif({ quality: 50 }).toBuffer(),
      resized.clone().webp({ quality: 80 }).toBuffer()
    ]);

    await persistDerivative(avifPath, avif);
    await persistDerivative(webpPath, webp);
    variants.avif.push({ width, src: publicUrl(avifPath) });
    variants.webp.push({ width, src: publicUrl(webpPath) });
  }

  return {
    src: publicUrl(filePath),
    width: sourceWidth,
    height: sourceHeight,
    variants
  };
}

// Renders one deterministic TypeScript manifest so runtime code stays typed
// without loading or parsing a second JSON file in the browser.
function renderManifest(entries) {
  const manifest = Object.fromEntries(entries.map(entry => [entry.src, entry]));
  return `/* Generated by scripts/generate-images.mjs. Do not edit manually. */
export interface GeneratedImageVariant {
  width: number;
  src: string;
}

export interface GeneratedImageEntry {
  src: string;
  width: number;
  height: number;
  variants: {
    avif: GeneratedImageVariant[];
    webp: GeneratedImageVariant[];
  };
}

export const generatedImageManifest: Record<string, GeneratedImageEntry> = ${JSON.stringify(manifest, null, 2)};
`;
}

// Generates every responsive derivative, or verifies the committed output when
// called with --check. Generation clears only the dedicated output directory.
async function main() {
  if (!CHECK_ONLY) {
    await rm(OUTPUT_ROOT, { recursive: true, force: true });
  }

  const entries = [];
  for (const source of await sourceFiles()) {
    const entry = await generateEntry(source);
    if (entry) entries.push(entry);
  }

  const manifest = renderManifest(entries);
  if (CHECK_ONLY) {
    const existingManifest = await readFile(MANIFEST_FILE, "utf8");
    if (existingManifest !== manifest) {
      throw new Error(`Generated manifest is stale: ${relative(ROOT, MANIFEST_FILE)}`);
    }
  } else {
    await mkdir(dirname(MANIFEST_FILE), { recursive: true });
    await writeFile(MANIFEST_FILE, manifest);
  }

  console.log(`${CHECK_ONLY ? "Verified" : "Generated"} ${entries.length} responsive image sets.`);
}

await main();
