/* Generated by scripts/generate-images.mjs. Do not edit manually. */
export interface GeneratedImageVariant {
  width: number;
  src: string;
}

export interface GeneratedImageEntry {
  src: string;
  width: number;
  height: number;
  variants: {
    avif: GeneratedImageVariant[];
    webp: GeneratedImageVariant[];
  };
}

export const generatedImageManifest: Record<string, GeneratedImageEntry> = {
  "/me-pictures/ARRRRRR.png": {
    "src": "/me-pictures/ARRRRRR.png",
    "width": 1536,
    "height": 2048,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/ARRRRRR/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/ARRRRRR/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/me-pictures/ARRRRRR/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/ARRRRRR/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/ARRRRRR/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/me-pictures/ARRRRRR/1200.webp"
        }
      ]
    }
  },
  "/me-pictures/BAH-Professional.png": {
    "src": "/me-pictures/BAH-Professional.png",
    "width": 500,
    "height": 500,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/BAH-Professional/400.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/BAH-Professional/400.webp"
        }
      ]
    }
  },
  "/me-pictures/Bernstein-Cool.jpeg": {
    "src": "/me-pictures/Bernstein-Cool.jpeg",
    "width": 602,
    "height": 752,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Bernstein-Cool/400.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Bernstein-Cool/400.webp"
        }
      ]
    }
  },
  "/me-pictures/Bernstein-Grabbing-Bag.jpeg": {
    "src": "/me-pictures/Bernstein-Grabbing-Bag.jpeg",
    "width": 752,
    "height": 501,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Bernstein-Grabbing-Bag/400.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Bernstein-Grabbing-Bag/400.webp"
        }
      ]
    }
  },
  "/me-pictures/Cool-Nutcracker-Guy.png": {
    "src": "/me-pictures/Cool-Nutcracker-Guy.png",
    "width": 1440,
    "height": 1903,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Cool-Nutcracker-Guy/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/Cool-Nutcracker-Guy/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/me-pictures/Cool-Nutcracker-Guy/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Cool-Nutcracker-Guy/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/Cool-Nutcracker-Guy/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/me-pictures/Cool-Nutcracker-Guy/1200.webp"
        }
      ]
    }
  },
  "/me-pictures/Cool-Shot.png": {
    "src": "/me-pictures/Cool-Shot.png",
    "width": 1170,
    "height": 1465,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Cool-Shot/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/Cool-Shot/800.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Cool-Shot/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/Cool-Shot/800.webp"
        }
      ]
    }
  },
  "/me-pictures/Funny-Hungry-Racoon.jpeg": {
    "src": "/me-pictures/Funny-Hungry-Racoon.jpeg",
    "width": 723,
    "height": 720,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Funny-Hungry-Racoon/400.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Funny-Hungry-Racoon/400.webp"
        }
      ]
    }
  },
  "/me-pictures/Grad-Dr-Park-GOAT.jpeg": {
    "src": "/me-pictures/Grad-Dr-Park-GOAT.jpeg",
    "width": 4032,
    "height": 3024,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Grad-Dr-Park-GOAT/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/Grad-Dr-Park-GOAT/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/me-pictures/Grad-Dr-Park-GOAT/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Grad-Dr-Park-GOAT/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/Grad-Dr-Park-GOAT/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/me-pictures/Grad-Dr-Park-GOAT/1200.webp"
        }
      ]
    }
  },
  "/me-pictures/Grad-Honors-Ceremony.jpeg": {
    "src": "/me-pictures/Grad-Honors-Ceremony.jpeg",
    "width": 4032,
    "height": 3024,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Grad-Honors-Ceremony/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/Grad-Honors-Ceremony/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/me-pictures/Grad-Honors-Ceremony/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Grad-Honors-Ceremony/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/Grad-Honors-Ceremony/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/me-pictures/Grad-Honors-Ceremony/1200.webp"
        }
      ]
    }
  },
  "/me-pictures/Graduation-Compsci-Guys.jpeg": {
    "src": "/me-pictures/Graduation-Compsci-Guys.jpeg",
    "width": 2304,
    "height": 1728,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Graduation-Compsci-Guys/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/Graduation-Compsci-Guys/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/me-pictures/Graduation-Compsci-Guys/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Graduation-Compsci-Guys/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/Graduation-Compsci-Guys/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/me-pictures/Graduation-Compsci-Guys/1200.webp"
        }
      ]
    }
  },
  "/me-pictures/Graduation-GradImages.jpeg": {
    "src": "/me-pictures/Graduation-GradImages.jpeg",
    "width": 387,
    "height": 499,
    "variants": {
      "avif": [
        {
          "width": 387,
          "src": "/_generated/me-pictures/Graduation-GradImages/387.avif"
        }
      ],
      "webp": [
        {
          "width": 387,
          "src": "/_generated/me-pictures/Graduation-GradImages/387.webp"
        }
      ]
    }
  },
  "/me-pictures/Rutgers-Team-Win.png": {
    "src": "/me-pictures/Rutgers-Team-Win.png",
    "width": 4032,
    "height": 3024,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Rutgers-Team-Win/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/Rutgers-Team-Win/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/me-pictures/Rutgers-Team-Win/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Rutgers-Team-Win/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/Rutgers-Team-Win/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/me-pictures/Rutgers-Team-Win/1200.webp"
        }
      ]
    }
  },
  "/me-pictures/Track-Senior-Night-Me.jpeg": {
    "src": "/me-pictures/Track-Senior-Night-Me.jpeg",
    "width": 800,
    "height": 600,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Track-Senior-Night-Me/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/Track-Senior-Night-Me/800.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/Track-Senior-Night-Me/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/Track-Senior-Night-Me/800.webp"
        }
      ]
    }
  },
  "/me-pictures/UPE-Ceremony-President.jpeg": {
    "src": "/me-pictures/UPE-Ceremony-President.jpeg",
    "width": 4032,
    "height": 3024,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/UPE-Ceremony-President/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/UPE-Ceremony-President/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/me-pictures/UPE-Ceremony-President/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/me-pictures/UPE-Ceremony-President/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/me-pictures/UPE-Ceremony-President/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/me-pictures/UPE-Ceremony-President/1200.webp"
        }
      ]
    }
  },
  "/projects/AI-Puzzle-Game-1.png": {
    "src": "/projects/AI-Puzzle-Game-1.png",
    "width": 1198,
    "height": 1231,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/AI-Puzzle-Game-1/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/AI-Puzzle-Game-1/800.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/AI-Puzzle-Game-1/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/AI-Puzzle-Game-1/800.webp"
        }
      ]
    }
  },
  "/projects/AI-Puzzle-Game-2.png": {
    "src": "/projects/AI-Puzzle-Game-2.png",
    "width": 1193,
    "height": 1231,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/AI-Puzzle-Game-2/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/AI-Puzzle-Game-2/800.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/AI-Puzzle-Game-2/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/AI-Puzzle-Game-2/800.webp"
        }
      ]
    }
  },
  "/projects/CapyMorph-1.png": {
    "src": "/projects/CapyMorph-1.png",
    "width": 1500,
    "height": 555,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/CapyMorph-1/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/CapyMorph-1/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/CapyMorph-1/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/CapyMorph-1/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/CapyMorph-1/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/CapyMorph-1/1200.webp"
        }
      ]
    }
  },
  "/projects/CapyMorph-2.png": {
    "src": "/projects/CapyMorph-2.png",
    "width": 1492,
    "height": 546,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/CapyMorph-2/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/CapyMorph-2/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/CapyMorph-2/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/CapyMorph-2/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/CapyMorph-2/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/CapyMorph-2/1200.webp"
        }
      ]
    }
  },
  "/projects/CapyMorph-3.png": {
    "src": "/projects/CapyMorph-3.png",
    "width": 1932,
    "height": 702,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/CapyMorph-3/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/CapyMorph-3/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/CapyMorph-3/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/CapyMorph-3/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/CapyMorph-3/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/CapyMorph-3/1200.webp"
        }
      ]
    }
  },
  "/projects/Chick-Count-1.png": {
    "src": "/projects/Chick-Count-1.png",
    "width": 307,
    "height": 147,
    "variants": {
      "avif": [
        {
          "width": 307,
          "src": "/_generated/projects/Chick-Count-1/307.avif"
        }
      ],
      "webp": [
        {
          "width": 307,
          "src": "/_generated/projects/Chick-Count-1/307.webp"
        }
      ]
    }
  },
  "/projects/Chick-Count-2.png": {
    "src": "/projects/Chick-Count-2.png",
    "width": 546,
    "height": 265,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Chick-Count-2/400.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Chick-Count-2/400.webp"
        }
      ]
    }
  },
  "/projects/KnowYourUni-1.png": {
    "src": "/projects/KnowYourUni-1.png",
    "width": 1896,
    "height": 841,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/KnowYourUni-1/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/KnowYourUni-1/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/KnowYourUni-1/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/KnowYourUni-1/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/KnowYourUni-1/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/KnowYourUni-1/1200.webp"
        }
      ]
    }
  },
  "/projects/KnowYourUni-2.png": {
    "src": "/projects/KnowYourUni-2.png",
    "width": 1829,
    "height": 602,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/KnowYourUni-2/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/KnowYourUni-2/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/KnowYourUni-2/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/KnowYourUni-2/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/KnowYourUni-2/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/KnowYourUni-2/1200.webp"
        }
      ]
    }
  },
  "/projects/KnowYourUni-3.png": {
    "src": "/projects/KnowYourUni-3.png",
    "width": 1965,
    "height": 940,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/KnowYourUni-3/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/KnowYourUni-3/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/KnowYourUni-3/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/KnowYourUni-3/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/KnowYourUni-3/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/KnowYourUni-3/1200.webp"
        }
      ]
    }
  },
  "/projects/KnowYourUni-4.png": {
    "src": "/projects/KnowYourUni-4.png",
    "width": 1963,
    "height": 941,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/KnowYourUni-4/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/KnowYourUni-4/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/KnowYourUni-4/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/KnowYourUni-4/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/KnowYourUni-4/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/KnowYourUni-4/1200.webp"
        }
      ]
    }
  },
  "/projects/KnowYourUni-5.png": {
    "src": "/projects/KnowYourUni-5.png",
    "width": 1968,
    "height": 941,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/KnowYourUni-5/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/KnowYourUni-5/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/KnowYourUni-5/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/KnowYourUni-5/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/KnowYourUni-5/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/KnowYourUni-5/1200.webp"
        }
      ]
    }
  },
  "/projects/KnowYourUni-6.png": {
    "src": "/projects/KnowYourUni-6.png",
    "width": 1957,
    "height": 941,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/KnowYourUni-6/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/KnowYourUni-6/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/KnowYourUni-6/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/KnowYourUni-6/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/KnowYourUni-6/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/KnowYourUni-6/1200.webp"
        }
      ]
    }
  },
  "/projects/Lunara-1.png": {
    "src": "/projects/Lunara-1.png",
    "width": 1892,
    "height": 1056,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Lunara-1/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Lunara-1/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Lunara-1/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Lunara-1/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Lunara-1/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Lunara-1/1200.webp"
        }
      ]
    }
  },
  "/projects/Lunara-2.png": {
    "src": "/projects/Lunara-2.png",
    "width": 1881,
    "height": 1062,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Lunara-2/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Lunara-2/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Lunara-2/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Lunara-2/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Lunara-2/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Lunara-2/1200.webp"
        }
      ]
    }
  },
  "/projects/Lunara-3.png": {
    "src": "/projects/Lunara-3.png",
    "width": 1875,
    "height": 942,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Lunara-3/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Lunara-3/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Lunara-3/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Lunara-3/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Lunara-3/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Lunara-3/1200.webp"
        }
      ]
    }
  },
  "/projects/Lunara-4.png": {
    "src": "/projects/Lunara-4.png",
    "width": 1878,
    "height": 950,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Lunara-4/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Lunara-4/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Lunara-4/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Lunara-4/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Lunara-4/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Lunara-4/1200.webp"
        }
      ]
    }
  },
  "/projects/Lunara-5.png": {
    "src": "/projects/Lunara-5.png",
    "width": 1870,
    "height": 1067,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Lunara-5/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Lunara-5/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Lunara-5/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Lunara-5/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Lunara-5/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Lunara-5/1200.webp"
        }
      ]
    }
  },
  "/projects/Lunara-6.png": {
    "src": "/projects/Lunara-6.png",
    "width": 1891,
    "height": 935,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Lunara-6/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Lunara-6/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Lunara-6/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Lunara-6/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Lunara-6/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Lunara-6/1200.webp"
        }
      ]
    }
  },
  "/projects/Lunara-7.png": {
    "src": "/projects/Lunara-7.png",
    "width": 1890,
    "height": 933,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Lunara-7/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Lunara-7/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Lunara-7/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Lunara-7/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Lunara-7/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Lunara-7/1200.webp"
        }
      ]
    }
  },
  "/projects/Lunara-8.png": {
    "src": "/projects/Lunara-8.png",
    "width": 1888,
    "height": 941,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Lunara-8/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Lunara-8/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Lunara-8/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Lunara-8/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Lunara-8/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Lunara-8/1200.webp"
        }
      ]
    }
  },
  "/projects/MOVE4WELLNESS-1.png": {
    "src": "/projects/MOVE4WELLNESS-1.png",
    "width": 327,
    "height": 650,
    "variants": {
      "avif": [
        {
          "width": 327,
          "src": "/_generated/projects/MOVE4WELLNESS-1/327.avif"
        }
      ],
      "webp": [
        {
          "width": 327,
          "src": "/_generated/projects/MOVE4WELLNESS-1/327.webp"
        }
      ]
    }
  },
  "/projects/MOVE4WELLNESS-2.png": {
    "src": "/projects/MOVE4WELLNESS-2.png",
    "width": 331,
    "height": 696,
    "variants": {
      "avif": [
        {
          "width": 331,
          "src": "/_generated/projects/MOVE4WELLNESS-2/331.avif"
        }
      ],
      "webp": [
        {
          "width": 331,
          "src": "/_generated/projects/MOVE4WELLNESS-2/331.webp"
        }
      ]
    }
  },
  "/projects/MOVE4WELLNESS-3.png": {
    "src": "/projects/MOVE4WELLNESS-3.png",
    "width": 330,
    "height": 616,
    "variants": {
      "avif": [
        {
          "width": 330,
          "src": "/_generated/projects/MOVE4WELLNESS-3/330.avif"
        }
      ],
      "webp": [
        {
          "width": 330,
          "src": "/_generated/projects/MOVE4WELLNESS-3/330.webp"
        }
      ]
    }
  },
  "/projects/MOVE4WELLNESS-4.png": {
    "src": "/projects/MOVE4WELLNESS-4.png",
    "width": 332,
    "height": 737,
    "variants": {
      "avif": [
        {
          "width": 332,
          "src": "/_generated/projects/MOVE4WELLNESS-4/332.avif"
        }
      ],
      "webp": [
        {
          "width": 332,
          "src": "/_generated/projects/MOVE4WELLNESS-4/332.webp"
        }
      ]
    }
  },
  "/projects/P2P-Encrypted-Chatroom-1.png": {
    "src": "/projects/P2P-Encrypted-Chatroom-1.png",
    "width": 897,
    "height": 830,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/P2P-Encrypted-Chatroom-1/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/P2P-Encrypted-Chatroom-1/800.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/P2P-Encrypted-Chatroom-1/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/P2P-Encrypted-Chatroom-1/800.webp"
        }
      ]
    }
  },
  "/projects/P2P-Encrypted-Chatroom-2.png": {
    "src": "/projects/P2P-Encrypted-Chatroom-2.png",
    "width": 912,
    "height": 832,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/P2P-Encrypted-Chatroom-2/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/P2P-Encrypted-Chatroom-2/800.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/P2P-Encrypted-Chatroom-2/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/P2P-Encrypted-Chatroom-2/800.webp"
        }
      ]
    }
  },
  "/projects/P2P-Encrypted-Chatroom-3.png": {
    "src": "/projects/P2P-Encrypted-Chatroom-3.png",
    "width": 910,
    "height": 832,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/P2P-Encrypted-Chatroom-3/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/P2P-Encrypted-Chatroom-3/800.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/P2P-Encrypted-Chatroom-3/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/P2P-Encrypted-Chatroom-3/800.webp"
        }
      ]
    }
  },
  "/projects/Parallel-Query-Processing-System-1.png": {
    "src": "/projects/Parallel-Query-Processing-System-1.png",
    "width": 2599,
    "height": 1309,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Parallel-Query-Processing-System-1/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Parallel-Query-Processing-System-1/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Parallel-Query-Processing-System-1/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Parallel-Query-Processing-System-1/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Parallel-Query-Processing-System-1/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Parallel-Query-Processing-System-1/1200.webp"
        }
      ]
    }
  },
  "/projects/Parallel-Query-Processing-System-2.png": {
    "src": "/projects/Parallel-Query-Processing-System-2.png",
    "width": 2600,
    "height": 1302,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Parallel-Query-Processing-System-2/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Parallel-Query-Processing-System-2/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Parallel-Query-Processing-System-2/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Parallel-Query-Processing-System-2/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Parallel-Query-Processing-System-2/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Parallel-Query-Processing-System-2/1200.webp"
        }
      ]
    }
  },
  "/projects/Parallel-Query-Processing-System-3.png": {
    "src": "/projects/Parallel-Query-Processing-System-3.png",
    "width": 2601,
    "height": 1308,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Parallel-Query-Processing-System-3/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Parallel-Query-Processing-System-3/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Parallel-Query-Processing-System-3/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Parallel-Query-Processing-System-3/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Parallel-Query-Processing-System-3/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Parallel-Query-Processing-System-3/1200.webp"
        }
      ]
    }
  },
  "/projects/Parallel-Query-Processing-System-4.png": {
    "src": "/projects/Parallel-Query-Processing-System-4.png",
    "width": 2597,
    "height": 1310,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Parallel-Query-Processing-System-4/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Parallel-Query-Processing-System-4/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Parallel-Query-Processing-System-4/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Parallel-Query-Processing-System-4/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Parallel-Query-Processing-System-4/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Parallel-Query-Processing-System-4/1200.webp"
        }
      ]
    }
  },
  "/projects/Parallel-Query-Processing-System-5.png": {
    "src": "/projects/Parallel-Query-Processing-System-5.png",
    "width": 2599,
    "height": 1302,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Parallel-Query-Processing-System-5/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Parallel-Query-Processing-System-5/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Parallel-Query-Processing-System-5/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Parallel-Query-Processing-System-5/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Parallel-Query-Processing-System-5/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Parallel-Query-Processing-System-5/1200.webp"
        }
      ]
    }
  },
  "/projects/Perishless-1.png": {
    "src": "/projects/Perishless-1.png",
    "width": 1280,
    "height": 720,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Perishless-1/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Perishless-1/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Perishless-1/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Perishless-1/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Perishless-1/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Perishless-1/1200.webp"
        }
      ]
    }
  },
  "/projects/Perishless-2.png": {
    "src": "/projects/Perishless-2.png",
    "width": 1280,
    "height": 720,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Perishless-2/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Perishless-2/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Perishless-2/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Perishless-2/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Perishless-2/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Perishless-2/1200.webp"
        }
      ]
    }
  },
  "/projects/Perishless-3.png": {
    "src": "/projects/Perishless-3.png",
    "width": 1280,
    "height": 720,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Perishless-3/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Perishless-3/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Perishless-3/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Perishless-3/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Perishless-3/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Perishless-3/1200.webp"
        }
      ]
    }
  },
  "/projects/Perishless-4.png": {
    "src": "/projects/Perishless-4.png",
    "width": 1280,
    "height": 720,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Perishless-4/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Perishless-4/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Perishless-4/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Perishless-4/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Perishless-4/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Perishless-4/1200.webp"
        }
      ]
    }
  },
  "/projects/Perishless-5.png": {
    "src": "/projects/Perishless-5.png",
    "width": 1280,
    "height": 720,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Perishless-5/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Perishless-5/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Perishless-5/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Perishless-5/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Perishless-5/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Perishless-5/1200.webp"
        }
      ]
    }
  },
  "/projects/Portfolio-Website.png": {
    "src": "/projects/Portfolio-Website.png",
    "width": 1883,
    "height": 948,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Portfolio-Website/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Portfolio-Website/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Portfolio-Website/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Portfolio-Website/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Portfolio-Website/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Portfolio-Website/1200.webp"
        }
      ]
    }
  },
  "/projects/Poultry-Analytics-1.png": {
    "src": "/projects/Poultry-Analytics-1.png",
    "width": 1902,
    "height": 958,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Poultry-Analytics-1/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Poultry-Analytics-1/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Poultry-Analytics-1/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Poultry-Analytics-1/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Poultry-Analytics-1/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Poultry-Analytics-1/1200.webp"
        }
      ]
    }
  },
  "/projects/Poultry-Analytics-2-Redacted.png": {
    "src": "/projects/Poultry-Analytics-2-Redacted.png",
    "width": 1902,
    "height": 958,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Poultry-Analytics-2-Redacted/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Poultry-Analytics-2-Redacted/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Poultry-Analytics-2-Redacted/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Poultry-Analytics-2-Redacted/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Poultry-Analytics-2-Redacted/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Poultry-Analytics-2-Redacted/1200.webp"
        }
      ]
    }
  },
  "/projects/Poultry-Analytics-3.png": {
    "src": "/projects/Poultry-Analytics-3.png",
    "width": 1902,
    "height": 958,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Poultry-Analytics-3/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Poultry-Analytics-3/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Poultry-Analytics-3/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Poultry-Analytics-3/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Poultry-Analytics-3/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Poultry-Analytics-3/1200.webp"
        }
      ]
    }
  },
  "/projects/Rova-1.png": {
    "src": "/projects/Rova-1.png",
    "width": 1440,
    "height": 2000,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Rova-1/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Rova-1/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Rova-1/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Rova-1/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Rova-1/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Rova-1/1200.webp"
        }
      ]
    }
  },
  "/projects/Rova-2.png": {
    "src": "/projects/Rova-2.png",
    "width": 1440,
    "height": 1000,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Rova-2/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Rova-2/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Rova-2/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Rova-2/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Rova-2/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Rova-2/1200.webp"
        }
      ]
    }
  },
  "/projects/Rova-3.png": {
    "src": "/projects/Rova-3.png",
    "width": 1440,
    "height": 1000,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Rova-3/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Rova-3/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Rova-3/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Rova-3/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Rova-3/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Rova-3/1200.webp"
        }
      ]
    }
  },
  "/projects/Rova-4.png": {
    "src": "/projects/Rova-4.png",
    "width": 1440,
    "height": 1000,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Rova-4/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Rova-4/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Rova-4/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Rova-4/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Rova-4/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Rova-4/1200.webp"
        }
      ]
    }
  },
  "/projects/Rova-5.png": {
    "src": "/projects/Rova-5.png",
    "width": 1440,
    "height": 1000,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Rova-5/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Rova-5/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Rova-5/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Rova-5/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Rova-5/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Rova-5/1200.webp"
        }
      ]
    }
  },
  "/projects/Shakespearean-LLM-1.png": {
    "src": "/projects/Shakespearean-LLM-1.png",
    "width": 1603,
    "height": 1186,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Shakespearean-LLM-1/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Shakespearean-LLM-1/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Shakespearean-LLM-1/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Shakespearean-LLM-1/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Shakespearean-LLM-1/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Shakespearean-LLM-1/1200.webp"
        }
      ]
    }
  },
  "/projects/Stock-Portfolio-Management-System-1.png": {
    "src": "/projects/Stock-Portfolio-Management-System-1.png",
    "width": 2457,
    "height": 1267,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-1/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-1/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-1/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-1/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-1/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-1/1200.webp"
        }
      ]
    }
  },
  "/projects/Stock-Portfolio-Management-System-2.png": {
    "src": "/projects/Stock-Portfolio-Management-System-2.png",
    "width": 2463,
    "height": 1267,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-2/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-2/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-2/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-2/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-2/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-2/1200.webp"
        }
      ]
    }
  },
  "/projects/Stock-Portfolio-Management-System-3.png": {
    "src": "/projects/Stock-Portfolio-Management-System-3.png",
    "width": 2463,
    "height": 1267,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-3/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-3/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-3/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-3/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-3/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-3/1200.webp"
        }
      ]
    }
  },
  "/projects/Stock-Portfolio-Management-System-4.png": {
    "src": "/projects/Stock-Portfolio-Management-System-4.png",
    "width": 2482,
    "height": 1265,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-4/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-4/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-4/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-4/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-4/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-4/1200.webp"
        }
      ]
    }
  },
  "/projects/Stock-Portfolio-Management-System-5.png": {
    "src": "/projects/Stock-Portfolio-Management-System-5.png",
    "width": 2462,
    "height": 1268,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-5/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-5/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-5/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-5/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-5/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Stock-Portfolio-Management-System-5/1200.webp"
        }
      ]
    }
  },
  "/projects/TestIfAI-1.png": {
    "src": "/projects/TestIfAI-1.png",
    "width": 1887,
    "height": 840,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/TestIfAI-1/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/TestIfAI-1/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/TestIfAI-1/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/TestIfAI-1/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/TestIfAI-1/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/TestIfAI-1/1200.webp"
        }
      ]
    }
  },
  "/projects/TestIfAI-2.png": {
    "src": "/projects/TestIfAI-2.png",
    "width": 1886,
    "height": 935,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/TestIfAI-2/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/TestIfAI-2/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/TestIfAI-2/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/TestIfAI-2/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/TestIfAI-2/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/TestIfAI-2/1200.webp"
        }
      ]
    }
  },
  "/projects/TestIfAI-3.png": {
    "src": "/projects/TestIfAI-3.png",
    "width": 1883,
    "height": 978,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/TestIfAI-3/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/TestIfAI-3/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/TestIfAI-3/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/TestIfAI-3/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/TestIfAI-3/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/TestIfAI-3/1200.webp"
        }
      ]
    }
  },
  "/projects/TestIfAI-4.png": {
    "src": "/projects/TestIfAI-4.png",
    "width": 1883,
    "height": 974,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/TestIfAI-4/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/TestIfAI-4/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/TestIfAI-4/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/TestIfAI-4/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/TestIfAI-4/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/TestIfAI-4/1200.webp"
        }
      ]
    }
  },
  "/projects/Vault-Assistant-1.png": {
    "src": "/projects/Vault-Assistant-1.png",
    "width": 1440,
    "height": 900,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Vault-Assistant-1/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Vault-Assistant-1/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Vault-Assistant-1/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Vault-Assistant-1/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Vault-Assistant-1/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Vault-Assistant-1/1200.webp"
        }
      ]
    }
  },
  "/projects/Vault-Assistant-2.png": {
    "src": "/projects/Vault-Assistant-2.png",
    "width": 1440,
    "height": 900,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Vault-Assistant-2/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Vault-Assistant-2/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Vault-Assistant-2/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Vault-Assistant-2/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Vault-Assistant-2/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Vault-Assistant-2/1200.webp"
        }
      ]
    }
  },
  "/projects/Vault-Assistant-3.png": {
    "src": "/projects/Vault-Assistant-3.png",
    "width": 1440,
    "height": 900,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Vault-Assistant-3/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Vault-Assistant-3/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Vault-Assistant-3/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Vault-Assistant-3/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Vault-Assistant-3/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Vault-Assistant-3/1200.webp"
        }
      ]
    }
  },
  "/projects/Vault-Assistant-4.png": {
    "src": "/projects/Vault-Assistant-4.png",
    "width": 1440,
    "height": 900,
    "variants": {
      "avif": [
        {
          "width": 400,
          "src": "/_generated/projects/Vault-Assistant-4/400.avif"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Vault-Assistant-4/800.avif"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Vault-Assistant-4/1200.avif"
        }
      ],
      "webp": [
        {
          "width": 400,
          "src": "/_generated/projects/Vault-Assistant-4/400.webp"
        },
        {
          "width": 800,
          "src": "/_generated/projects/Vault-Assistant-4/800.webp"
        },
        {
          "width": 1200,
          "src": "/_generated/projects/Vault-Assistant-4/1200.webp"
        }
      ]
    }
  }
};
