/*
  Topic definitions for the topic pages (src/components/topic-page/*),
  served at /<key> (canonical) with /topics/<key> kept as a working alias.

  A "topic" is a curated lens over the projects — "AI Engineering",
  "Full-Stack Dev", etc. Each topic page reuses the live project data from
  src/assets/projects/ (via PROJECT_BY_SLUG) and the live tool icons from
  experience.ts (via getTechnologyIcon); THIS file only holds the editorial
  curation that can't be derived: which projects belong to a topic, the blurb,
  technical decisions, and the headline tool list.

  Quick edit guide:
  - Add a topic: add an entry to `topics` and its key to `topicOrder` (order
    controls the switcher tabs and which topic a project's tag links to — the
    first topic in this list that contains a project wins).
  - `projects` are real project SLUGS — the lowercase, dash-separated names in
    the /projects/<slug> URLs, generated by slug() in lib/terminalHomeData.ts
    (e.g. "Vault Assistant" → "vault-assistant"). Unknown slugs are skipped.
  - `tools` are display names; icons are resolved automatically through the
    shared alias map in experience.ts, so "OpenAI API", "Google Gemini",
    "Scikit-Learn", "Node.js", "Cryptography", etc. all work. A tool with no
    known icon still renders as a text-only pill.
  - `decisions` is a short framing paragraph about tradeoffs that show up
    across the topic's projects (rendered under the matches section).
*/

export interface TopicDef {
  title: string; // big hollow header, e.g. "AI Engineering"
  label: string; // short switcher-tab text, e.g. "ai-engineering"
  command: string; // fake shell line rendered as "# <command>"
  intro: string; // one-paragraph blurb under the header
  decisions: string; // short technical-decisions framing for the topic
  projects: string[]; // real project slugs, in display order
  tools: string[]; // headline tool names (icons resolved via getTechnologyIcon)
}

// Order of the switcher tabs; topicOrder[0] is the default topic (served at /topics)
export const topicOrder: string[] = [
  "ai-engineering",
  "full-stack-development",
  "data-science-ml",
  "developer-tools",
  "systems-and-security",
  "hackathon-projects"
];

export const topics: Record<string, TopicDef> = {
  "ai-engineering": {
    title: "AI Engineering",
    label: "ai-engineering",
    command: 'grep -r "ai" ~/projects --include=*.md',
    intro:
      "Projects where the model is the product — LLM apps, RAG pipelines, computer vision, and applied ML shipped end to end.",
    decisions:
      "Prefer grounded retrieval and editable outputs over black-box chat. Keep humans in the loop for high-stakes domains (healthcare, education, farm decisions), and favor local or inspectable pipelines when the data should not leave the machine.",
    projects: [
      "lunara",
      "rova",
      "vault-assistant",
      "testifai",
      "perishless",
      "shakespearean-personality-llm-augmentation",
      "knowyouruni",
      "poultry-farm-data-analytics-dashboard",
      "computer-vision-chick-counting"
    ],
    tools: [
      "Python",
      "PyTorch",
      "TensorFlow",
      "HuggingFace",
      "LangChain",
      "OpenAI API",
      "Google Gemini",
      "Scikit-Learn"
    ]
  },
  "full-stack-development": {
    title: "Full-Stack Dev",
    label: "full-stack",
    command: 'grep -r "full-stack" ~/projects --include=*.md',
    intro:
      "Front-to-back builds — React frontends, API backends, databases, and the deploys that keep them up.",
    decisions:
      "Ship a real React + API loop early, then harden auth, storage, and deployment. Prefer boring, known stacks (Vite, FastAPI, Postgres/Firebase) so most of the risk sits in product logic, not framework novelty.",
    projects: [
      "lunara",
      "perishless",
      "capymorph",
      "rova",
      "claritycash",
      "stock-portfolio-management-system",
      "portfolio-website"
    ],
    tools: ["React", "TypeScript", "JavaScript", "Node.js", "FastAPI", "Vite", "TailwindCSS", "Docker"]
  },
  "data-science-ml": {
    title: "Data Science & ML",
    label: "data-science-ml",
    command: 'grep -r "data" ~/projects --include=*.ipynb',
    intro:
      "ETL, analysis, and models on real datasets — dashboards, decision support, and ML that answers actual questions.",
    decisions:
      "Start with data quality and reproducible notebooks before the fancy model. Dashboards and Quarto reports stay decision-support tools — they surface signal for a person, they do not auto-act on it.",
    projects: [
      "data-science-stuff",
      "poultry-farm-data-analytics-dashboard",
      "computer-vision-chick-counting",
      "knowyouruni",
      "shakespearean-personality-llm-augmentation"
    ],
    tools: ["Python", "Pandas", "NumPy", "Scikit-Learn", "TensorFlow", "Jupyter", "Plotly"]
  },
  "developer-tools": {
    title: "Developer Tools",
    label: "dev-tools",
    command: 'grep -r "cli" ~/projects --include=*.md',
    intro:
      "Tools built for people who live in the editor — local-first assistants, benchmarks, and workflow utilities.",
    decisions:
      "Optimize for local control and inspectability: BM25 over hosted embeddings when the vault stays on disk, swap-in agent backends, and measurable benchmarks instead of vibes. A little setup friction is fine if the evidence stays visible.",
    projects: [
      "vault-assistant",
      "parallel-query-processing-system",
      "algorithm-performance-benchmarker",
      "portfolio-website"
    ],
    tools: ["TypeScript", "Bun", "Git", "Linux", "Bash", "Docker"]
  },
  "systems-and-security": {
    title: "Systems & Security",
    label: "systems-security",
    command: 'grep -r "encryption" ~/projects --include=*.c',
    intro:
      "Closer to the metal — encryption, distributed query processing, and performance work in C and C++.",
    decisions:
      "Prefer explicit protocols and measurable performance over convenience wrappers. Encryption, concurrency, and query planning stay understandable when you own the byte-level details.",
    projects: [
      "encrypted-p2p-chatroom",
      "parallel-query-processing-system",
      "algorithm-performance-benchmarker"
    ],
    tools: ["C", "C++", "Python", "Cryptography", "WebSockets", "Linux", "Bash"]
  },
  "hackathon-projects": {
    title: "Hackathons",
    label: "hackathons",
    command: "journalctl --unit=hackathons --no-pager",
    intro:
      "Projects built under hackathon constraints, shaped by short timelines, team decisions, and demo-day feedback.",
    decisions:
      "Cut scope hard: one demable loop, editable LLM outputs, and a stack the team already knows. Post-hackathon work is where auth, data quality, and deployment catch up.",
    projects: ["knowyouruni", "testifai", "lunara", "rova", "perishless", "claritycash"],
    tools: ["React", "FastAPI", "AWS", "Python", "OpenAI API", "LangChain"]
  }
};
